default_language_version:
  python: python3.8
fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: "docs"
        additional_dependencies: &flake8-deps
          - flake8-bugbear==22.4.25
          - flake8-comprehensions==3.10.0
          - flake8-mutable==1.2.0
          - flake8-print==5.0.0
          - flake8-quotes==3.3.1
          - flake8-simplify==0.19.2
          - flake8-requirements==1.5.4
          - pep8-naming==0.13.0
          - pydocstyle==6.1.1
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: name-tests-test
        args: [--django]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: local
    hooks:
      - id: wrong-pytest-imports
        name: wrong pytest imports
        language: pygrep
        entry: ^from _pytest
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        exclude: "(docs|setup.py)"
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    - id: yesqa
      additional_dependencies: *flake8-deps
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check
