name: Tag package

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel bumpver
          pip install -r requirements.dev.txt
          pip install .
      - name: Test with pytest
        run: pytest
      - name: push new tag
        run: |
          # Git config
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Tag and its message
          bumpver update -n
          eval $(bumpver show -n --env)
          changes=$(sed -n '/^++++$/,/^++++++++/p' CHANGELOG.rst | sed '1d;$d' | sed '$d')
          message=$(echo -e "\n${changes}")

          # Finalize changelog
          sed -i "s/^++++$/++++\n\n${CURRENT_VERSION}\n$(printf '+%.0s' $(seq 2 $(echo ${CURRENT_VERSION} | wc -c | tr -d ' ')))/" CHANGELOG.rst

          # Commit changes
          git add CHANGELOG.rst
          git commit --amend --no-edit

          # Tag the commit
          git tag -a "${CURRENT_VERSION}" -m "${message}" -f

          # Push commit and tag
          git push origin
          git push origin "${CURRENT_VERSION}"
