name: Tag package

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.dev.txt
          pip install .
      - name: Test with pytest
        run: pytest
      - name: push new tag
        run: |
          tag=$(date '+%Y.%m.%d')
          msg=$(echo release)
          message="${tag}: \n${msg}"

          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          sed -i "s/\(^release *= *\).*/\1\"${tag}\"/" config.py
          sed -i "s/^++++$/++++\n\n${tag}\n++++++++++/" CHANGELOG.rst

          git add config.py CHANGELOG.rst
          git commit -m "chore: Release ${tag}"
          git tag -a "${tag}" -m "${message}"
          git push origin
          git push origin -f "${tag}"
